In [1]:
import tensorflow as tf

In [9]:
t1=tf.constant([1,2,3])
t2=tf.constant([3,4,5])
t3=tf.constant([6,7,8])

# tf.math.add_n()

In [10]:
ad=tf.math.add_n([t1,t2,t3])
ad.numpy()

array([10, 13, 16])

# tf.math.accumulate_n() - same as addition

In [13]:
ac=tf.math.accumulate_n([t1,t2,t3])
ac.numpy()

array([10, 13, 16])

# tf.math.subtract()

In [12]:
sub=tf.math.subtract(t1,t2)
sub

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-2, -2, -2])>

# tf.math.multiply()

In [14]:
mul=tf.math.multiply(t1,t2)
mul.numpy()

array([ 3,  8, 15])

# tf.math.scalar_mul()

In [22]:
a=tf.constant([1,2,3])
alpha=3
res=tf.math.scalar_mul(alpha,a)
res.numpy()

array([3, 6, 9])

# tf.math.top_k()

In [28]:
t=tf.constant([1,2,3,4,5])
values,indices=tf.math.top_k(t,k=2)
print(f"index - {indices}: values - {values}")

index - [4 3]: values - [5 4]


# tf.math.reduce_max()

In [29]:
t=tf.constant([[1,2,3],[2,3,4]])
ans=tf.math.reduce_max(t)
print(ans)

tf.Tensor(4, shape=(), dtype=int32)


# tf.math.argmax()

In [32]:
t = tf.constant([1, 3, 2, 4])

result = tf.math.argmax(t)
print(f"index of max element : {result.numpy()}")

index of max element : 3


# tf.math.squared_difference()

In [35]:
t1=tf.constant([1,2])
t2=tf.constant([3,4])
res=tf.math.squared_difference(t1,t2)
res.numpy()

array([4, 4])

# tf.math.rsqrt()

In [37]:
v = tf.constant([1.0, 4.0, 9.0])
ans=tf.math.rsqrt(v)
ans.numpy()

array([1.        , 0.5       , 0.33333334], dtype=float32)

# tf.math.floormod()

In [38]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([2, 2, 2])
v=tf.math.floormod(t1,t2)
v.numpy()

array([1, 0, 1])

# tf.math.softplus()

In [49]:
v=tf.constant([[-1.0, 0.0, 1.0]])

In [51]:
tf.math.softplus(v)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.3132617, 0.6931472, 1.3132616]], dtype=float32)>

# tf.math.l2_normalize()

In [54]:
tensor = tf.constant([1.0, 2.0, 3.0])

In [55]:
res=tf.math.l2_normalize(tensor)

In [56]:
res.numpy()

array([0.26726124, 0.5345225 , 0.8017837 ], dtype=float32)

# tf.math.segment_max()

In [59]:
a=tf.constant([1,2,3,4,5,6])
segment_ids=tf.constant([0,0,1,1,2,2])

In [60]:
s_max=tf.math.segment_max(a,segment_ids)
s_max

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

# tf.math.unsorted_segment_mean()

In [ ]:
a=tf.constant([1,2,3,4,5,6])
segment_ids=tf.constant([0,0,1,1,2,2])

# Trignometry

In [42]:
tensor = tf.constant([1.0, 0.5, -0.5])

# Sine
result_sin = tf.math.sin(tensor)
print("Sine:", result_sin.numpy())

# Hyperbolic Sine
result_sinh = tf.math.sinh(tensor)
print("Hyperbolic Sine:", result_sinh.numpy())

# Cosine
result_cos = tf.math.cos(tensor)
print("Cosine:", result_cos.numpy())

# Hyperbolic Cosine
result_cosh = tf.math.cosh(tensor)
print("Hyperbolic Cosine:", result_cosh.numpy())

# Tangent
result_tan = tf.math.tan(tensor)
print("Tangent:", result_tan.numpy())

# Hyperbolic Tangent
result_tanh = tf.math.tanh(tensor)
print("Hyperbolic Tangent:", result_tanh.numpy())

# Inverse Trigonometric Functions
result_acos = tf.math.acos(tensor)
print("Arccosine:", result_acos.numpy())

result_acosh = tf.math.acosh(tensor)
print("Inverse Hyperbolic Cosine:", result_acosh.numpy())

result_atan = tf.math.atan(tensor)
print("Arctangent:", result_atan.numpy())

result_atanh = tf.math.atanh(tensor)
print("Inverse Hyperbolic Tangent:", result_atanh.numpy())


Sine: [ 0.84147096  0.47942555 -0.47942555]
Hyperbolic Sine: [ 1.1752012  0.5210953 -0.5210953]
Cosine: [0.5403023  0.87758255 0.87758255]
Hyperbolic Cosine: [1.5430807 1.127626  1.127626 ]
Tangent: [ 1.5574077  0.5463025 -0.5463025]
Hyperbolic Tangent: [ 0.7615942   0.46211717 -0.46211717]
Arccosine: [0.        1.0471976 2.0943952]
Inverse Hyperbolic Cosine: [ 0. nan nan]
Arctangent: [ 0.7853982  0.4636476 -0.4636476]
Inverse Hyperbolic Tangent: [        inf  0.54930615 -0.54930615]


# Comparision operators

In [46]:
# Define two tensors
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([2, 2, 2])

# Perform element-wise comparisons
less_result = tf.math.less(tensor1, tensor2)
less_equal_result = tf.math.less_equal(tensor1, tensor2)
greater_result = tf.math.greater(tensor1, tensor2)
greater_equal_result=tf.math.greater_equal(tensor1,tensor2)
equal_result = tf.math.equal(tensor1, tensor2)
not_equal_result = tf.math.not_equal(tensor1, tensor2)

print("Less:", less_result.numpy())              
print("Less Equal:", less_equal_result.numpy())  
print("Greater:", greater_result.numpy())  
print("Greater equal:",greater_equal_result.numpy())
print("Equal:", equal_result.numpy())            
print("Not Equal:", not_equal_result.numpy())   


Less: [ True False False]
Less Equal: [ True  True False]
Greater: [False False  True]
Greater equal: [False  True  True]
Equal: [False  True False]
Not Equal: [ True False  True]


# Bitwise operators

In [48]:
# Define two tensors
tensor1 = tf.constant([5, 6, 7])  # Binary: 101, 110, 111
tensor2 = tf.constant([3, 5, 2])  # Binary: 011, 101, 010

# Bitwise AND
result_and = tf.bitwise.bitwise_and(tensor1, tensor2)
print("Bitwise AND:", result_and.numpy())  # Output: [1 4 2] (Binary: 001, 100, 010)

# Bitwise OR
result_or = tf.bitwise.bitwise_or(tensor1, tensor2)
print("Bitwise OR:", result_or.numpy())    # Output: [7 7 7] (Binary: 111, 111, 111)

# Bitwise XOR
result_xor = tf.bitwise.bitwise_xor(tensor1, tensor2)
print("Bitwise XOR:", result_xor.numpy())  # Output: [6 3 5] (Binary: 110, 011, 101)

# Bitwise NOT
result_not = tf.bitwise.invert(tensor1)
print("Bitwise NOT (tensor1):", result_not.numpy())  # Output: [-6 -7 -8]

# Left Shift
result_left_shift = tf.bitwise.left_shift(tensor1, 2)  # Shifting left by 2 bits
print("Left Shift (tensor1):", result_left_shift.numpy())    # Output: [20 24 28] (Binary: 10100, 11000, 11100)

# Right Shift
result_right_shift = tf.bitwise.right_shift(tensor1, 1)  # Shifting right by 1 bit
print("Right Shift (tensor1):", result_right_shift.numpy())    # Output: [2 3 3] (Binary: 10, 11, 11)


Bitwise AND: [1 4 2]
Bitwise OR: [7 7 7]
Bitwise XOR: [6 3 5]
Bitwise NOT (tensor1): [-6 -7 -8]
Left Shift (tensor1): [20 24 28]
Right Shift (tensor1): [2 3 3]
