In [1]:
import tensorflow as tf

Deconvolution layers, also known as transposed convolutional layers, are used primarily for upsampling feature maps to higher resolutions. 

**They are the opposite of convolutional layers in the sense that while convolutional layers reduce spatial dimensions (downsampling), transposed convolutional layers increase spatial dimensions (upsampling)**

**They are commonly used in generative models, such as autoencoders and GANs, and in tasks like image segmentation where output resolution needs to be increased.**

## 1] Conv1DTranspose

**Usage:** Applies a 1D transposed convolution operation to temporal data.
    
**Common Use Cases:** Upsampling in time-series analysis, audio signal processing.
    
**Input Shape:** (batch_size, length, channels)
    
**Output Shape:** (batch_size, new_length, filters), where new_length is determined by the stride and padding.

In [2]:
# Create dummy data
batch_size = 4
length = 20
channels = 3
data = tf.random.normal((batch_size, length, channels))

In [5]:
data

<tf.Tensor: shape=(4, 20, 3), dtype=float32, numpy=
array([[[-1.3042297 ,  0.81605494, -1.4418066 ],
        [-0.51623255,  1.6227818 ,  0.52197963],
        [-0.44857183,  0.28065056,  0.09434219],
        [-0.5693795 , -1.6555096 , -1.9822632 ],
        [ 0.4111531 ,  0.5860732 , -0.73745424],
        [-0.90838784, -0.26562226, -0.92266923],
        [-0.83375126, -0.11666463, -0.80912286],
        [-0.8307641 , -0.08491044,  1.4282374 ],
        [-0.8934029 ,  0.0237517 ,  0.7685022 ],
        [-0.2444032 , -0.744352  , -0.92004186],
        [ 0.06091975,  0.41631696,  0.02218096],
        [ 0.80591416,  1.1105126 ,  0.34485793],
        [ 1.2468008 ,  0.7766783 , -0.16948718],
        [ 0.6525162 ,  0.28115746,  1.5096353 ],
        [ 1.4817511 , -0.81973684, -0.5101296 ],
        [-0.5144517 ,  0.4979476 , -2.0183516 ],
        [-0.6763321 , -0.5658817 ,  0.2883967 ],
        [ 0.74347126,  0.25776184,  0.8001155 ],
        [-0.12640058,  0.23745283, -2.5101738 ],
        [-0.16399

In [3]:
conv1d_transpose_layer=tf.keras.layers.Conv1DTranspose(filters=5,kernel_size=3,strides=2,padding='same')

In [4]:
conv1d_transpose_data=conv1d_transpose_layer(data)
conv1d_transpose_data

<tf.Tensor: shape=(4, 40, 5), dtype=float32, numpy=
array([[[ 2.57813096e-01,  1.35193430e-02,  3.76088172e-01,
          3.23020160e-01,  7.25831270e-01],
        [ 2.15837270e-01,  6.92620277e-01,  1.02234519e+00,
         -4.46273357e-01,  1.30030215e+00],
        [ 4.87871170e-02,  7.80636549e-01,  1.00789070e+00,
          7.15775192e-02, -1.93390220e-01],
        [-3.66857827e-01, -1.62871853e-01,  6.72721416e-02,
         -3.39270473e-01,  5.98346233e-01],
        [-6.80660784e-01,  3.95106882e-01,  9.29397047e-02,
         -7.96332598e-01, -8.45262706e-01],
        [-1.47335634e-01, -2.78636664e-02,  1.66491464e-01,
          8.66141394e-02,  2.63719052e-01],
        [ 1.23046577e+00, -6.59705579e-01, -9.82451499e-01,
         -1.51286587e-01,  1.93330914e-01],
        [ 6.67242587e-01,  8.26238513e-01,  8.62382174e-01,
          1.94537103e-01,  3.32964122e-01],
        [ 1.47246456e+00, -7.86654502e-02,  2.88220376e-01,
          1.56988883e+00,  1.26910245e+00],
        [ 3.

## 2] Conv2DTranspose

**Usage:** Applies a 2D transposed convolution operation to image data.
    
**Common Use Cases:** Image upsampling in image segmentation, super-resolution, and generative models.
    
**Input Shape:** (batch_size, height, width, channels)
    
**Output Shape:** (batch_size, new_height, new_width, filters), where new_height and new_width are determined by the stride and padding.

In [6]:
# Create dummy data
batch_size = 4
height = 16
width = 16
channels = 3

In [7]:
data=tf.random.normal((batch_size,height,width,channels))
data

<tf.Tensor: shape=(4, 16, 16, 3), dtype=float32, numpy=
array([[[[-1.2101884 ,  0.26768178, -0.58548933],
         [ 1.8475155 ,  0.3562815 , -0.2672291 ],
         [-0.43965417, -1.1077658 , -0.23028955],
         ...,
         [-0.11181469, -1.4144493 , -0.40154514],
         [ 1.4412411 , -0.16779979, -2.6580615 ],
         [ 0.43701252, -1.7112586 , -0.92948115]],

        [[-0.35407886,  0.72220343, -0.72783434],
         [-0.11575587, -0.5295027 ,  0.1766752 ],
         [ 0.12342939, -0.14461665,  0.39272436],
         ...,
         [-0.4721194 , -0.26628107, -0.64824194],
         [ 1.7073281 , -1.8891654 , -0.54689026],
         [ 0.45464635, -0.43675974,  0.22309911]],

        [[-0.45843652, -0.66083527, -1.3413732 ],
         [ 1.5625881 , -1.1464506 , -0.55106837],
         [-0.9396778 ,  1.2111233 , -0.48670268],
         ...,
         [ 1.9345212 ,  1.0449731 , -0.4322553 ],
         [ 0.82043886, -0.93989754, -2.242138  ],
         [ 0.07234995, -0.07280167, -1.4798967 ]

In [8]:
conv2d_transpose_layer=tf.keras.layers.Conv2DTranspose(filters=5,kernel_size=(3,3),strides=2,padding='same')

In [9]:
conv2d_data=conv2d_transpose_layer(data)

In [10]:
conv2d_data

<tf.Tensor: shape=(4, 32, 32, 5), dtype=float32, numpy=
array([[[[-5.91291785e-02,  3.34940106e-01, -1.54755563e-01,
           4.56106424e-01,  3.09271693e-01],
         [-3.73865925e-02, -2.00244263e-01, -8.36659744e-02,
           1.64446831e-01, -3.28908563e-01],
         [-4.25952226e-01, -1.74235687e-01,  2.87685931e-01,
          -5.93943894e-02, -5.09187162e-01],
         ...,
         [ 1.94596857e-01, -3.81087393e-01, -5.54360390e-01,
          -3.88067871e-01,  3.99170905e-01],
         [ 9.06330168e-01,  5.02329469e-01,  4.61111873e-01,
          -6.87547773e-02, -1.22521305e+00],
         [-3.12722743e-01, -5.21076657e-02, -2.62980431e-01,
           1.79539874e-01,  5.16843557e-01]],

        [[-3.02411199e-01, -2.55691912e-02, -1.05303220e-01,
           1.71539620e-01, -2.41934955e-01],
         [-2.41216421e-01, -2.10627615e-01,  3.14745009e-02,
           9.49767753e-02,  1.88148066e-01],
         [ 5.67732573e-01,  4.97278571e-01,  3.45405817e-01,
          -3.496108

## 3] Conv3DTranspose

**Usage:** Applies a 3D transposed convolution operation to volumetric data.
    
**Common Use Cases:** Upsampling in 3D medical imaging, video frame reconstruction.
    
**Input Shape:** (batch_size, depth, height, width, channels)
    
**Output Shape:** (batch_size, new_depth, new_height, new_width, filters), where new_depth, new_height, and new_width are determined by the stride and padding.

In [11]:
# Create dummy data
batch_size = 4
depth = 8
height = 8
width = 8
channels = 3

In [12]:
data = tf.random.normal((batch_size, depth, height, width, channels))

In [13]:
data

<tf.Tensor: shape=(4, 8, 8, 8, 3), dtype=float32, numpy=
array([[[[[ 7.52883255e-01, -6.18464231e-01,  1.42844605e+00],
          [ 3.31510961e-01, -1.98961139e+00,  1.09626222e+00],
          [ 8.16277146e-01,  3.16893101e-01, -7.04185069e-02],
          ...,
          [ 1.35424465e-01, -2.65294939e-01, -1.31911802e+00],
          [-5.25241315e-01,  1.10486150e+00, -1.04395294e+00],
          [ 3.13413680e-01, -2.79681146e-01, -2.71937013e-01]],

         [[ 2.70695835e-01,  2.02915505e-01,  3.63804251e-01],
          [ 3.84144217e-01, -1.53306139e+00, -1.88982457e-01],
          [ 3.82676154e-01, -4.77193564e-01,  8.74911025e-02],
          ...,
          [ 1.07769656e+00,  8.63348246e-02, -8.23320270e-01],
          [-6.30348623e-01,  6.06509507e-01, -9.94134963e-01],
          [-5.78640580e-01,  6.80402875e-01,  1.34999561e+00]],

         [[-6.54036939e-01, -1.08081973e+00, -2.08171725e+00],
          [-9.97823238e-01,  4.84038949e-01, -1.52245602e-02],
          [-1.02753246e+00,

In [14]:
conv3d_transpose_layer = tf.keras.layers.Conv3DTranspose(filters=10, kernel_size=(3, 3, 3), strides=2, padding='same')

In [15]:
conv3d_transpose_d=conv3d_transpose_layer(data)

In [16]:
conv3d_transpose_d

<tf.Tensor: shape=(4, 16, 16, 16, 10), dtype=float32, numpy=
array([[[[[ 6.18845001e-02,  8.87253881e-03, -1.85111433e-01, ...,
            2.05671683e-01, -2.03758597e-01, -1.13690048e-02],
          [ 8.17729160e-02, -5.76302186e-02,  9.07611847e-02, ...,
            6.80703595e-02,  1.09747112e-01,  1.96256280e-01],
          [ 1.57147259e-01,  8.63177255e-02, -5.81716478e-01, ...,
            1.33324400e-01, -2.07427889e-02, -3.30287069e-02],
          ...,
          [-1.20554239e-01,  8.21193010e-02, -4.35639545e-02, ...,
           -1.20417304e-01,  4.21695411e-04, -1.19741946e-01],
          [-1.51962727e-01,  1.56060293e-01,  2.72950232e-01, ...,
            1.86773643e-01, -5.45815676e-02,  8.05984065e-02],
          [-1.26512451e-02,  2.44259574e-02,  2.22785603e-02, ...,
           -2.72305310e-02, -8.99308734e-03, -3.08623724e-03]],

         [[ 2.00102717e-01, -1.38673885e-02,  4.97389697e-02, ...,
           -1.24598145e-01,  7.38126785e-02, -7.00865984e-02],
          [ 