In [1]:
import tensorflow as tf

# 1] tf.keras.layers.Flatten

Reshapes a n-dimensional input to a single n-1 dimensional tensor.

**Use Case: After convolutional layers to flatten the output before feeding it to dense layers.**

### Example : 1 - Without using expand dims

In [2]:
# Sample 3D data (e.g., a single 3x3 "image" with 2 channels)
data = tf.constant([[[1, 2], [3, 4], [5, 6]], 
                    [[7, 8], [9, 10], [11, 12]], 
                    [[13, 14], [15, 16], [17, 18]]], dtype=tf.float32)

In [3]:
print("Original data shape : ",data.shape)

Original data shape :  (3, 3, 2)


In [11]:
print("Original data : ")
data.numpy()

Original data : 


array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]], dtype=float32)

In [4]:
flatten_layer=tf.keras.layers.Flatten()

In [5]:
flatten_data=flatten_layer(data)

In [14]:
#(3,3,2)-->(3,3*2)=(3,6)
print("Flattened data shape : ",flatten_data.shape)

Flattened data shape :  (3, 6)


In [12]:
print("Flattened data : ")
flatten_data.numpy()

Flattened data : 


array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.]], dtype=float32)

### Example 2 - With using expand dims

In [19]:
# Sample 3D data (e.g., a single 3x3 "image" with 2 channels)
data = tf.constant([[[1, 2], [3, 4], [5, 6]], 
                    [[7, 8], [9, 10], [11, 12]], 
                    [[13, 14], [15, 16], [17, 18]]], dtype=tf.float32)

#### (h,w,channels):(3,3,2)-->(batchsize,h,w,channels):(1,3,3,2)

In [22]:
expanded_data=tf.expand_dims(data,axis=0)
expanded_data

<tf.Tensor: shape=(1, 3, 3, 2), dtype=float32, numpy=
array([[[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.]]]], dtype=float32)>

In [23]:
flatten=tf.keras.layers.Flatten()

In [26]:
#(1,3,3,2)-->(1,3*3*2)=(1,18)
flattened_data=flatten(expanded_data)

In [27]:
flattened_data

<tf.Tensor: shape=(1, 18), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18.]], dtype=float32)>

# 2] tf.keras.layers.Dense

Fully connected layer where each neuron receives input from all neurons in the previous layer.

**Use Case:**

   **Typically used at the end of the network for classification or regression tasks,**
   **but can also be used in intermediate layers for feature extraction and transformation.**

Number of neurons:
    
    1] Binary classification (0 or 1) : Dense(1)
        
    2] Multiclass Classification (n classes) : Dense(n)
        
    3] Regression : Dense(1) note : default activation func : Linear for regression task

In [38]:
# Sample data (2D)
data = tf.constant([[1, 2, 3, 4]], dtype=tf.float32)

In [39]:
dense_layer=tf.keras.layers.Dense(3,activation='leaky_relu')

In [40]:
dense_data=dense_layer(data)

In [41]:
dense_data.numpy()

array([[-0.3963044,  2.972586 ,  3.16109  ]], dtype=float32)

# 3] tf.keras.layers.Dropout

1] The Dropout layer is typically **applied after fully connected (dense) layers** 
   or sometimes **after convolutional layers** in a neural network

2] The main purpose of dropout is to **prevent overfitting by randomly setting a fraction of the input units to 0 at each update    during training time**

3]

In [46]:
# Sample data
data = tf.constant([[1, 2, 3, 4, 5]], dtype=tf.float32)

print("Original data:")

data.numpy()

Original data:


array([[1., 2., 3., 4., 5.]], dtype=float32)

In [47]:
dropout_layer=tf.keras.layers.Dropout(0.2)

In [48]:
output=dropout_layer(data,training=True)  # Set training=True to apply dropout

In [49]:
print("Dropped O/P data : ")
output.numpy()

Dropped O/P data : 


array([[1.25, 0.  , 3.75, 5.  , 6.25]], dtype=float32)