In [1]:
import tensorflow as tf

# MaxPooling

### 1] MaxPooling1D

**Usage:** Applies a 1D max pooling operation along the temporal axis.

**Common Use Cases:** Downsampling in time-series analysis, audio signal processing.

**Input Shape:** (batch_size, length, channels)

**Output Shape:** (batch_size, pooled_length, channels), where pooled_length is determined by the pool size and strides.

In [2]:
batch_size=16
length=5
channels=3

In [3]:
data=tf.random.normal((batch_size,length,channels))

In [7]:
data

<tf.Tensor: shape=(16, 5, 3), dtype=float32, numpy=
array([[[-7.85487235e-01,  1.52255625e-01, -3.51061821e-01],
        [-5.94544351e-01, -1.34426558e+00, -6.77379906e-01],
        [-9.08519924e-01, -2.80860979e-02,  1.97676396e+00],
        [ 1.63695335e+00,  1.40711129e+00, -1.14645195e+00],
        [ 1.08876258e-01,  7.94985116e-01, -6.69212341e-01]],

       [[-7.15458870e-01, -8.69714022e-01, -1.36428893e+00],
        [ 1.58814228e+00,  3.45366336e-02,  1.64298177e+00],
        [ 1.19009781e+00, -7.60177851e-01, -2.04356718e+00],
        [ 4.46953565e-01,  4.67106581e-01, -3.16648781e-01],
        [ 9.17515516e-01,  1.25261247e+00,  2.79876375e+00]],

       [[ 5.77834308e-01,  9.01856184e-01,  7.02857554e-01],
        [ 8.00940573e-01,  3.37093115e-01,  1.95659846e-01],
        [ 3.61154377e-01,  5.41393638e-01, -1.37656510e-01],
        [ 4.01117295e-01, -1.07793689e+00,  1.53723955e+00],
        [ 8.60796392e-01, -1.18453777e+00, -2.61096269e-01]],

       [[ 5.55151820e-01, -

In [4]:
maxpool_1d_layer=tf.keras.layers.MaxPooling1D(pool_size=2,strides=2)

In [5]:
max_pool_data=maxpool_1d_layer(data)

In [6]:
max_pool_data

<tf.Tensor: shape=(16, 2, 3), dtype=float32, numpy=
array([[[-0.59454435,  0.15225562, -0.35106182],
        [ 1.6369534 ,  1.4071113 ,  1.976764  ]],

       [[ 1.5881423 ,  0.03453663,  1.6429818 ],
        [ 1.1900978 ,  0.46710658, -0.31664878]],

       [[ 0.8009406 ,  0.9018562 ,  0.70285755],
        [ 0.4011173 ,  0.54139364,  1.5372396 ]],

       [[ 0.5551518 ,  0.22768936, -0.62709886],
        [ 1.9479841 , -0.1564309 ,  0.32636783]],

       [[ 0.49506685, -0.33799157,  2.4576762 ],
        [ 0.77031374,  0.78917503,  1.9037608 ]],

       [[ 0.6782417 ,  1.347314  ,  0.3608988 ],
        [-0.07499801,  1.0038186 ,  0.8340309 ]],

       [[ 0.47997406, -0.2956299 ,  1.1545165 ],
        [ 0.02416976,  1.6494447 , -1.2144641 ]],

       [[ 0.2528772 ,  0.20419197, -0.33600843],
        [ 1.087702  , -0.5448439 ,  0.66276366]],

       [[-0.27213845,  0.497863  ,  0.8687129 ],
        [-0.3251964 ,  1.0873244 ,  0.11077904]],

       [[-0.05493263,  0.3459989 ,  0.6777175 ],

### 2] MaxPooling2D

**Usage:** Applies a 2D max pooling operation along the spatial dimensions (height, width).

**Common Use Cases:** Downsampling in image processing, computer vision tasks.

**Input Shape:** (batch_size, height, width, channels)

**Output Shape:** (batch_size, pooled_height, pooled_width, channels), where pooled_height and pooled_width are determined by the pool size and strides.

In [8]:
batch_size = 4
height = 32
width = 32
channels = 3

In [9]:
data=tf.random.normal((batch_size,height,width,channels))

In [13]:
data

<tf.Tensor: shape=(4, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.08429897e+00, -6.72334790e-01,  1.40121818e+00],
         [-1.59023666e+00,  1.20225586e-01,  4.58195508e-01],
         [-1.46500838e+00, -2.20619276e-01,  1.27325642e+00],
         ...,
         [-1.57488966e+00,  8.53501618e-01, -2.70444334e-01],
         [-3.76909614e-01,  9.14338350e-01,  1.74228752e+00],
         [-2.40350872e-01,  3.48610103e-01,  9.53741610e-01]],

        [[-2.22097898e+00,  9.54301596e-01, -2.61531293e-01],
         [-3.60100091e-01,  1.45396554e+00,  1.96044254e+00],
         [-1.60126239e-01,  1.56063247e+00,  1.26607561e+00],
         ...,
         [-1.79756057e+00,  1.43663538e+00,  3.29862773e-01],
         [-2.63911068e-01,  1.04975545e+00,  6.55460000e-01],
         [-8.62895906e-01,  1.07759726e+00,  1.44322217e+00]],

        [[ 6.56558692e-01,  2.28480244e+00,  8.85201335e-01],
         [-3.73426288e-01, -6.17779553e-01,  8.41130674e-01],
         [ 9.49503109e-02, -2.05848496e-02, 

In [10]:
maxpool_2d_layer=tf.keras.layers.MaxPooling2D(pool_size=(2,2),strides=(2,2))

In [11]:
max_pool_2d=maxpool_2d_layer(data)

In [12]:
max_pool_2d

<tf.Tensor: shape=(4, 16, 16, 3), dtype=float32, numpy=
array([[[[ 1.084299  ,  1.4539655 ,  1.9604425 ],
         [ 1.0196515 ,  1.5606325 ,  1.2732564 ],
         [ 1.4877439 ,  0.49055004,  0.97703826],
         ...,
         [ 1.6748854 ,  1.5051063 ,  0.981514  ],
         [ 0.05095318,  2.184981  ,  1.1982112 ],
         [-0.24035087,  1.0775973 ,  1.7422875 ]],

        [[ 0.6565587 ,  2.2848024 ,  0.9604145 ],
         [ 0.16248025,  0.76752406,  0.51022846],
         [ 0.6370767 ,  1.830057  ,  0.35670212],
         ...,
         [ 0.06925076,  1.1161994 ,  2.0320957 ],
         [ 1.7951082 ,  1.7089487 ,  1.508605  ],
         [ 1.3456266 ,  1.5598452 ,  1.7547547 ]],

        [[ 0.7512952 ,  2.6366372 ,  2.1751015 ],
         [ 0.9474952 ,  0.96999323,  1.03713   ],
         [ 1.3518901 ,  2.5427568 ,  1.3263316 ],
         ...,
         [ 0.7239778 ,  0.7844032 ,  1.2994983 ],
         [ 2.0311234 ,  0.6479652 ,  1.9112452 ],
         [ 1.7512901 ,  1.0694263 ,  0.0193026 ]

### 3] MaxPooling3D

**Usage:** Applies a 3D max pooling operation along the spatial dimensions (depth, height, width).

**Common Use Cases:** Downsampling in volumetric data processing, medical imaging.

**Input Shape:** (batch_size, depth, height, width, channels)

**Output Shape:** (batch_size, pooled_depth, pooled_height, pooled_width, channels), where pooled_depth, pooled_height, and pooled_width are determined by the pool size and strides.

In [14]:
batch_size = 4
depth = 16
height = 32
width = 32
channels = 3

In [15]:
data=tf.random.normal((batch_size,depth,height,width,channels))

In [16]:
data

<tf.Tensor: shape=(4, 16, 32, 32, 3), dtype=float32, numpy=
array([[[[[ 1.86356336e-01, -1.33518982e+00,  1.24732006e+00],
          [ 1.84624779e+00, -1.42549384e+00,  2.55179375e-01],
          [ 1.24504912e+00,  2.28706646e+00, -2.19188884e-01],
          ...,
          [-7.68547237e-01, -4.79607791e-01,  3.93045157e-01],
          [-1.51946336e-01,  3.25734615e-01,  5.16406834e-01],
          [-5.78293085e-01,  9.35106993e-01, -4.11825627e-01]],

         [[ 1.98774230e+00, -2.59604144e+00,  2.70889491e-01],
          [ 3.53837341e-01,  6.49417043e-01,  1.97182879e-01],
          [-1.06419885e+00, -9.34060872e-01,  4.77950007e-01],
          ...,
          [-4.99460906e-01,  1.75275171e+00,  1.33946812e+00],
          [-1.27446198e+00, -1.48573488e-01,  3.18060070e-01],
          [-8.62060249e-01, -6.59656584e-01,  7.12307572e-01]],

         [[ 3.68515819e-01,  9.62024271e-01, -5.42878568e-01],
          [ 9.11689579e-01, -1.16016877e+00,  2.34124988e-01],
          [ 3.93507808e-

In [17]:
maxpool_3d_layer=tf.keras.layers.MaxPooling3D(pool_size=(2,2,2),strides=(2,2,2))

In [18]:
maxpool_3d_d=maxpool_3d_layer(data)

In [19]:
maxpool_3d_d

<tf.Tensor: shape=(4, 8, 16, 16, 3), dtype=float32, numpy=
array([[[[[ 1.9877423e+00,  8.4049809e-01,  1.2473201e+00],
          [ 1.2450491e+00,  2.2870665e+00,  1.4540910e+00],
          [ 1.2291443e+00,  1.2930870e+00,  1.2356799e+00],
          ...,
          [ 2.5428271e+00,  1.3314883e+00,  7.8917146e-01],
          [ 1.8420322e+00,  1.7527517e+00,  1.5223870e+00],
          [-1.5194634e-01,  9.3510699e-01,  1.7510384e+00]],

         [[ 9.1168958e-01,  1.2371529e+00,  1.1312282e+00],
          [ 1.9072685e+00,  1.5483499e+00,  1.0729640e+00],
          [ 2.2706685e+00,  9.5049076e-02,  7.2420615e-01],
          ...,
          [ 1.6175759e+00,  1.6720712e+00,  6.1585760e-01],
          [ 1.7671909e+00,  6.6395468e-01,  2.1649525e+00],
          [ 2.0994780e+00,  1.8207211e+00,  1.7290413e+00]],

         [[ 1.3250829e+00,  1.5019405e+00,  1.1982574e+00],
          [ 1.5138971e+00,  2.8239793e-01,  1.5661069e+00],
          [ 2.6703157e+00,  1.6948339e+00,  1.4445046e+00],
       

# AveragePooling

### 1] AveragePooling1D

**Usage:** Applies a 1D average pooling operation along the temporal axis.

**Common Use Cases:** Downsampling in time-series analysis, audio signal processing.

**Input Shape:** (batch_size, length, channels)

**Output Shape:** (batch_size, pooled_length, channels), where pooled_length is determined by the pool size and strides.

In [21]:
batch_size=16
length=10
channels=3

In [22]:
data=tf.random.normal((batch_size,length,channels))

In [25]:
data

<tf.Tensor: shape=(16, 10, 3), dtype=float32, numpy=
array([[[-1.02734447e+00, -5.23631752e-01, -9.08517003e-01],
        [ 1.09203196e+00, -6.11913323e-01,  1.54960620e+00],
        [-1.01865061e-01, -1.32402813e+00, -2.00945425e+00],
        [-3.98779184e-01, -1.14426923e+00, -1.67476976e+00],
        [ 6.52120650e-01,  1.46959545e-02, -1.83254313e+00],
        [-8.63187015e-01, -1.37336218e+00, -4.25013959e-01],
        [-2.79273200e+00, -1.89142323e+00, -1.78528413e-01],
        [-4.96014953e-01, -1.54207015e+00,  1.10742235e+00],
        [-1.11413419e+00,  3.38006467e-01, -2.12760758e+00],
        [-2.63866395e-01, -1.89028993e-01,  3.76499817e-02]],

       [[-8.06528389e-01,  1.02803671e+00,  1.68446898e-01],
        [-5.46227515e-01, -5.43858647e-01,  1.72525215e+00],
        [-5.87009072e-01, -5.83556481e-02, -8.05019557e-01],
        [ 1.91492870e-01,  9.35250521e-01, -2.70254970e-01],
        [ 5.18557802e-02,  2.28502795e-01, -5.59485197e-01],
        [ 2.13961577e+00,  3.7

In [24]:
avg_pooling_1dlayer=tf.keras.layers.AveragePooling1D(pool_size=2,strides=2)

In [27]:
avg_pool_1d_data=avg_pooling_1dlayer(data)

In [28]:
avg_pool_1d_data

<tf.Tensor: shape=(16, 5, 3), dtype=float32, numpy=
array([[[ 3.23437452e-02, -5.67772508e-01,  3.20544600e-01],
        [-2.50322133e-01, -1.23414874e+00, -1.84211206e+00],
        [-1.05533183e-01, -6.79333091e-01, -1.12877858e+00],
        [-1.64437342e+00, -1.71674669e+00,  4.64446962e-01],
        [-6.89000309e-01,  7.44887367e-02, -1.04497886e+00]],

       [[-6.76377952e-01,  2.42089033e-01,  9.46849525e-01],
        [-1.97758108e-01,  4.38447446e-01, -5.37637234e-01],
        [ 1.09573579e+00,  3.02993059e-01, -9.56679136e-02],
        [-1.64979029e+00,  7.87808597e-01,  1.64962456e-01],
        [ 4.35617656e-01, -6.05493188e-01,  7.23674297e-01]],

       [[-9.01620984e-02,  5.84869623e-01,  2.28191853e-01],
        [ 9.80909705e-01,  3.61409962e-01, -9.89859998e-02],
        [-4.90129501e-01,  6.61587834e-01,  6.48584664e-01],
        [ 4.99478541e-02, -7.37174392e-01,  7.44588375e-01],
        [ 9.59014654e-01, -2.72419691e-01, -5.87136149e-01]],

       [[ 9.42705512e-01,  

### 2] AveragePooling2D

**Usage:** Applies a 2D average pooling operation along the spatial dimensions (height, width).

**Common Use Cases:** Downsampling in image processing, computer vision tasks.

**Input Shape:** (batch_size, height, width, channels)

**Output Shape:** (batch_size, pooled_height, pooled_width, channels), where pooled_height and pooled_width are determined by the pool size and strides.

In [29]:
batch_size=16
height=32
width=32
channels=3

In [30]:
data=tf.random.normal((batch_size,height,width,channels))

In [34]:
data

<tf.Tensor: shape=(16, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.15389180e+00, -1.11762989e+00, -9.09127891e-01],
         [ 9.05683458e-01, -8.18794489e-01,  9.77594495e-01],
         [ 1.25889480e+00,  6.47596896e-01,  4.79527302e-02],
         ...,
         [-5.47465801e-01,  6.19402468e-01,  1.03257549e+00],
         [ 8.40275824e-01, -9.44293570e-03, -1.51392624e-01],
         [ 1.21350431e+00, -7.38716304e-01,  4.04119372e-01]],

        [[ 5.66679239e-01,  1.73465729e+00, -1.89481229e-01],
         [-6.80909753e-01,  1.52718031e+00,  1.45947790e+00],
         [ 1.41104543e+00, -8.14401567e-01, -6.25530660e-01],
         ...,
         [-8.35400745e-02,  8.22609141e-02, -8.20049822e-01],
         [ 1.65167391e+00,  6.47427857e-01,  1.46015322e+00],
         [ 1.89061785e+00,  7.98302054e-01, -6.65023804e-01]],

        [[ 4.13944304e-01, -6.48414373e-01, -8.73376548e-01],
         [-5.19132674e-01, -1.80519235e+00,  9.13031995e-01],
         [-3.12772274e-01,  5.47513127e-01,

In [31]:
avg_pooling_2dlayer=tf.keras.layers.AveragePooling2D(pool_size=(2,2),strides=(2,2))

In [32]:
avg_pool_2d=avg_pooling_2dlayer(data)

In [33]:
avg_pool_2d

<tf.Tensor: shape=(16, 16, 16, 3), dtype=float32, numpy=
array([[[[ 4.86336201e-01,  3.31353307e-01,  3.34615827e-01],
         [ 1.02119148e+00,  2.98841596e-02,  1.20401323e-01],
         [-1.18537235e+00, -8.47991407e-02,  6.75298274e-03],
         ...,
         [ 7.28461087e-01, -1.50267273e-01, -5.65938294e-01],
         [-3.02034616e-01,  6.36757016e-01, -4.96586740e-01],
         [ 1.39901793e+00,  1.74392670e-01,  2.61964023e-01]],

        [[ 6.18748724e-01, -8.59095216e-01,  2.60686576e-01],
         [-3.54265034e-01, -1.51115194e-01,  1.23441972e-01],
         [ 1.15638661e+00,  3.69274795e-01, -5.39472461e-01],
         ...,
         [-1.06162357e+00,  4.72917706e-01, -9.40839291e-01],
         [ 3.84549871e-02,  2.94105113e-01, -6.41326785e-01],
         [-2.92523503e-01, -6.63694143e-01, -1.03593796e-01]],

        [[-3.91334683e-01,  2.69113123e-01,  6.69910192e-01],
         [ 1.51535884e-01, -2.61725783e-02,  9.57451582e-01],
         [-2.28633404e-01, -8.58797908e-01,

### 3] AveragePooling3D

**Usage:** Applies a 3D average pooling operation along the spatial dimensions (depth, height, width).

**Common Use Cases:** Downsampling in volumetric data processing, medical imaging.

**Input Shape:** (batch_size, depth, height, width, channels)

**Output Shape:** (batch_size, pooled_depth, pooled_height, pooled_width, channels), where pooled_depth, pooled_height, and pooled_width are determined by the pool size and strides.

In [35]:
batch_size=16
depth=3
height=32
width=32
channels=3

In [36]:
data=tf.random.normal((batch_size,depth,height,width,channels))

In [40]:
data

<tf.Tensor: shape=(16, 3, 32, 32, 3), dtype=float32, numpy=
array([[[[[ 1.14306915e+00,  1.32708684e-01, -1.29706457e-01],
          [ 2.38322541e-02,  6.42081276e-02, -1.14318204e+00],
          [-1.01322961e+00, -7.52637088e-02,  5.37493527e-01],
          ...,
          [ 1.13705063e+00,  7.70546079e-01, -1.74886441e+00],
          [-1.54734480e+00, -2.87110686e-01,  9.57975686e-01],
          [ 1.69415724e+00, -4.00584221e-01,  2.62746423e-01]],

         [[ 3.18301082e-01,  1.00161779e+00, -1.06942558e+00],
          [-2.13226765e-01, -3.97295356e-01,  8.85815382e-01],
          [-2.24513158e-01,  1.28193820e+00,  1.49196088e-01],
          ...,
          [ 1.00804472e+00,  5.48673570e-01,  4.31546986e-01],
          [-2.34069467e-01,  4.58318561e-01, -3.24270463e+00],
          [-2.21973348e+00, -6.65530980e-01, -1.57250452e+00]],

         [[-1.29356563e+00, -8.71840000e-01,  9.78109241e-01],
          [ 1.21453083e+00, -1.37121069e+00, -7.25803077e-01],
          [-3.38677585e-

In [37]:
avg_pooling_3dlayer=tf.keras.layers.AveragePooling3D(pool_size=(2,2,2),strides=(2,2,2))

In [38]:
avg_pool_3d_data=avg_pooling_3dlayer(data)

In [39]:
avg_pool_3d_data

<tf.Tensor: shape=(16, 1, 16, 16, 3), dtype=float32, numpy=
array([[[[[ 2.04936355e-01,  4.13654119e-01, -1.19957909e-01],
          [-4.66020346e-01, -1.04262255e-01, -2.04141662e-02],
          [ 6.34924099e-02,  5.08821249e-01,  2.35447794e-01],
          ...,
          [-6.84185863e-01,  1.39410794e-03, -3.80429476e-01],
          [ 4.52427953e-01,  4.71128911e-01, -5.91939017e-02],
          [ 1.42551214e-02, -2.34541655e-01, -3.91363978e-01]],

         [[ 2.08374038e-01, -2.85543740e-01, -7.36775994e-02],
          [-2.35391960e-01,  2.88805246e-01, -6.76310182e-01],
          [ 1.50854081e-01,  3.67700189e-01, -3.26809973e-01],
          ...,
          [-1.85491592e-01,  2.94101715e-01, -4.92324024e-01],
          [-2.53890336e-01, -1.04282454e-01, -2.60204315e-01],
          [-1.52814507e-01, -8.81284535e-01,  1.64400339e-02]],

         [[ 1.75931305e-01, -1.72664300e-02, -3.57709527e-02],
          [ 5.78652978e-01,  3.18098575e-01, -4.00769174e-01],
          [ 2.30405480e-

# GlobalPooling

### 1] GlobalMaxPooling1D

**Usage:** Applies a global max pooling operation along the temporal axis, reducing each feature map to a single value.

**Common Use Cases:** Reducing the dimensionality of temporal data.

**Input Shape:** (batch_size, length, channels)

**Output Shape:** (batch_size, channels)

In [42]:
batch_size=16
length=10
channels=3

In [43]:
data=tf.random.normal((batch_size,length,channels))

In [45]:
global_max_pool1d_layer=tf.keras.layers.GlobalMaxPooling1D()

In [46]:
global_1d_data=global_max_pool1d_layer(data)

In [47]:
global_1d_data

<tf.Tensor: shape=(16, 3), dtype=float32, numpy=
array([[1.4822236 , 2.087037  , 0.75436944],
       [0.5914418 , 1.7074605 , 0.8598967 ],
       [0.9734559 , 1.6035988 , 2.041354  ],
       [1.7677077 , 1.3923076 , 1.4426646 ],
       [0.5268746 , 1.572834  , 1.4121215 ],
       [1.2841866 , 1.7740192 , 0.9074514 ],
       [2.2152157 , 1.97147   , 1.0281984 ],
       [1.820745  , 1.1439208 , 2.8058162 ],
       [2.7648244 , 2.4698877 , 1.3114902 ],
       [2.023441  , 2.79568   , 1.0687773 ],
       [0.729483  , 1.575981  , 1.1992965 ],
       [0.6678301 , 0.97189224, 0.73477244],
       [1.5947083 , 1.8456486 , 1.0015453 ],
       [1.5498124 , 0.80653507, 1.7732275 ],
       [1.3822742 , 1.3475348 , 1.24223   ],
       [1.8490208 , 1.0806438 , 2.0900562 ]], dtype=float32)>

### 2] GlobalMaxPooling2D

**Usage:** Applies a global max pooling operation along the spatial dimensions (height, width), reducing each feature map to a single value.

**Common Use Cases:** Reducing the dimensionality of image data.

**Input Shape:** (batch_size, height, width, channels)

**Output Shape:** (batch_size, channels)

In [41]:
batch_size=16
height=32
width=32
channels=3

In [48]:
data=tf.random.normal((batch_size,height,width,channels))

In [52]:
data

<tf.Tensor: shape=(16, 32, 32, 3), dtype=float32, numpy=
array([[[[ 5.92530239e-03, -2.52567083e-01,  1.51846159e+00],
         [ 3.40309441e-01, -1.22913994e-01, -4.76582885e-01],
         [-6.09670043e-01,  4.75065559e-01,  6.85775578e-01],
         ...,
         [ 8.66716266e-01, -4.41865861e-01,  1.82609415e+00],
         [-6.52218521e-01, -5.31070292e-01, -8.76421392e-01],
         [-2.95343399e-01,  2.06060350e-01,  5.05782604e-01]],

        [[ 8.30229998e-01, -1.23154771e+00, -1.07901609e+00],
         [-3.65173876e-01,  1.15771127e+00, -5.71665823e-01],
         [ 1.40420985e+00,  5.25858283e-01,  4.07601446e-01],
         ...,
         [-1.20514882e+00,  4.80170459e-01,  1.57595527e+00],
         [ 4.44778889e-01,  1.83871233e+00, -2.14168310e+00],
         [-3.10924232e-01,  3.71700883e-01, -7.59656072e-01]],

        [[-1.86073494e+00, -6.26016796e-01, -1.01166569e-01],
         [-2.19915390e-01, -2.56430596e-01,  4.85080779e-01],
         [-6.09144568e-01, -4.00473565e-01,

In [49]:
global_max_pool2d_layer=tf.keras.layers.GlobalMaxPooling2D()

In [50]:
global_2d_data=global_max_pool2d_layer(data)

In [51]:
global_2d_data

<tf.Tensor: shape=(16, 3), dtype=float32, numpy=
array([[3.4456944, 2.854403 , 3.0149548],
       [3.005785 , 3.164281 , 3.2536747],
       [3.164789 , 3.3266184, 3.8209376],
       [2.998955 , 4.0700083, 3.516204 ],
       [3.335958 , 3.0013523, 3.2353408],
       [3.0445232, 3.179205 , 3.2023609],
       [3.0090678, 3.2918446, 3.0340812],
       [2.686104 , 3.3345685, 2.7818108],
       [3.60909  , 3.2814224, 3.0579765],
       [3.380693 , 3.359608 , 3.378251 ],
       [3.2539623, 3.1875198, 3.7055109],
       [3.0591826, 3.4489362, 2.965807 ],
       [3.515796 , 3.8059905, 3.1019702],
       [3.2110977, 3.2131429, 2.7740257],
       [3.133708 , 3.3170667, 3.0234344],
       [3.1668925, 3.0831208, 3.0796008]], dtype=float32)>

### 3] GlobalMaxPooling3D

**Usage:** Applies a global max pooling operation along the spatial dimensions (depth, height, width), reducing each feature map to a single value.

**Common Use Cases:** Reducing the dimensionality of volumetric data.

**Input Shape:** (batch_size, depth, height, width, channels)

**Output Shape:** (batch_size, channels)

In [53]:
batch_size=16
depth=3
height=32
width=32
channels=3

In [54]:
data=tf.random.normal((batch_size,depth,height,width,channels))

In [58]:
data

<tf.Tensor: shape=(16, 3, 32, 32, 3), dtype=float32, numpy=
array([[[[[-3.07179242e-01, -1.16668046e+00, -1.72534502e+00],
          [ 4.07230347e-01, -1.13631713e+00,  8.73027682e-01],
          [-1.56206107e+00, -4.28546488e-01,  2.39195488e-02],
          ...,
          [ 1.46849811e-01,  1.33315539e+00, -1.24915683e+00],
          [ 6.30038798e-01,  4.73874100e-02, -7.61909068e-01],
          [-4.82015789e-01,  1.20731032e+00,  8.68607283e-01]],

         [[-1.15147126e+00, -2.15403008e+00,  1.26751649e+00],
          [-1.32628429e+00,  9.92737114e-02, -5.96769415e-02],
          [-9.28564295e-02,  1.03932559e+00, -1.55110645e+00],
          ...,
          [-4.80046898e-01,  1.91016090e+00,  6.76953316e-01],
          [-1.43245056e-01,  1.35440618e-01,  8.76136482e-01],
          [-2.11372137e-01,  1.16801047e+00,  2.11783186e-01]],

         [[ 6.39272947e-03,  1.88406754e+00, -1.93741143e-01],
          [ 4.42920178e-01, -1.41713250e+00,  5.80733061e-01],
          [ 5.81447005e-

In [55]:
global_max_pool3d_layer=tf.keras.layers.GlobalMaxPooling3D()

In [56]:
global_3d_data=global_max_pool3d_layer(data)

In [57]:
global_3d_data

<tf.Tensor: shape=(16, 3), dtype=float32, numpy=
array([[3.119004 , 3.8332717, 3.6989486],
       [3.9073045, 3.547158 , 3.9073837],
       [3.074048 , 3.29548  , 3.496152 ],
       [3.629428 , 3.1231415, 3.9547029],
       [3.5979524, 3.5017   , 3.5233352],
       [3.1226277, 3.456282 , 3.6838145],
       [3.8417442, 3.8064058, 3.3589609],
       [3.0855262, 3.567014 , 3.2359283],
       [3.6222904, 3.442684 , 3.3094194],
       [2.9762654, 3.409381 , 3.11679  ],
       [3.3431451, 3.2099082, 3.493145 ],
       [3.2122703, 3.20227  , 3.3842018],
       [4.034073 , 3.903443 , 3.3965516],
       [3.4074228, 3.7333956, 4.011336 ],
       [3.1766412, 3.6353765, 3.626131 ],
       [3.644657 , 3.3097944, 3.4534042]], dtype=float32)>

## What is channels in 1D data?

In the context of 1D data, the `channels` dimension typically indicates different features or types of information present at each time step. Here are some examples to illustrate this:

1. **Time-Series Data**: In a time-series dataset, `channels` could represent different variables recorded at each time step. For instance, in a multivariate time series of weather data, each channel might represent a different measurement such as temperature, humidity, and wind speed.

2. **Audio Data**: In an audio dataset, `channels` could represent different audio channels. For example, stereo audio has two channels (left and right).

3. **Sequential Data**: In other types of sequential data, `channels` could represent different aspects or features of the data at each sequence step. For example, in natural language processing, each channel might represent different embeddings or features extracted from text data.

In summary, the `channels` dimension in 1D data is used to represent the number of features or types of information present at each time step or sequence element.



### Why `channels` Dimension is Important:
- The `channels` dimension allows the network to handle multiple features or types of information at each time step.
- During convolution or pooling operations, each channel is processed independently, preserving the separate features while downsampling the sequence length.

This concept is analogous to how `channels` in 2D data (like images) represent different color channels (RGB), but in 1D data, it represents different features or measurements at each time step in the sequence.

In [ ]:
Pooling layer where to use?