In [1]:
import tensorflow as tf

# Tensors

# Tensor- Constant and its Operations

In [3]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[2,3],[4,5]])

In [4]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [5]:
b.numpy()

array([[2, 3],
       [4, 5]])

## Element-wise Operations

### add(), subtract(), multiply(), divide() operations

In [6]:
add=tf.add(a,b)
add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 9]])>

In [7]:
sub=tf.subtract(a,b)
sub

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1]])>

In [11]:
mul=tf.multiply(a,b)
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [13]:
div=tf.divide(a,b)
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5       , 0.66666667],
       [0.75      , 0.8       ]])>

## Reduction Operations

### reduce_x()  x--> sum(),mean(),max(),min()

In [15]:
summ=tf.reduce_sum(a)
summ.numpy()

10

In [16]:
mean=tf.reduce_mean(b)
mean.numpy()

3

In [18]:
maxx=tf.reduce_max(a)
maxx.numpy()

4

In [20]:
minn=tf.reduce_min(b)
minn.numpy()

2

## Matrix Operaions

### Matrix Multiplication

In [21]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

In [22]:
mat=tf.matmul(matrix_a,matrix_b)

In [24]:
mat.numpy()

array([[19, 22],
       [43, 50]])

### Transpose

In [25]:
transposed_mat=tf.transpose(matrix_a)
transposed_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

## Indexing and Slicing

### Indexing

In [27]:
matrix_a[0,1].numpy()

2

### Slicing

In [31]:
matrix_a[0:2,0:1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]])>

In [32]:
matrix_a[:,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## To get Shape of tensor - shape()

In [34]:
a=tf.constant([[2,3,4],[1,2,3]])

In [36]:
r_c=tf.shape(a)

In [37]:
r_c.numpy()

array([2, 3])

## To get dim of tensor - rank()

In [38]:
a=tf.constant([[2,3,4],[1,2,3]])

In [39]:
dim=tf.rank(a)

In [41]:
dim.numpy()

2

## To get size of tensor - size()

In [43]:
a=tf.constant([[2,3],[1,2]])

In [44]:
num_of_elements=tf.size(a)

In [45]:
num_of_elements.numpy()

4

## Reshaping - reshape(tensor,dim)

### Reshaping any dimenison to 1

In [46]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

In [47]:
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a_1d=tf.reshape(a,[-1])
a_1d.numpy()

array([1, 2, 3, 4, 5, 6])

In [55]:
# a to have 3 dimensions: 2 rows, 1 column, and 3 elements per row. 
tf.reshape(a,[2,1,3]).numpy()

array([[[1, 2, 3]],

       [[4, 5, 6]]])

## Expanding Dimensions - tf.expand_dims(tensor, axis)

In [56]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

In [57]:
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

In [59]:
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]])>

In [60]:
tf.expand_dims(a,axis=2)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

## Squeezing Dimensions - tf.squeeze(tensor, axis)

In [62]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

In [63]:
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
n=tf.expand_dims(a,axis=0)

In [70]:
n

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

In [69]:
tf.squeeze(n,axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [74]:
new_a=tf.reshape(a,[2,1,3])

In [75]:
new_a

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]])>

In [76]:
tf.squeeze(new_a,axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## Resizing