In [1]:
import tensorflow as tf

# Creating and Inspecting a Variable

In [2]:
v=tf.Variable([3,4])

In [3]:
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>

# Dimension, Size, Shape, and Data Type of a TensorFlow Variable

In [11]:
print('Dimension : ',tf.rank(v).numpy())
print("Size : ",tf.size(v).numpy())
print("Shape : ",v.shape)
print("Data type : ",v.dtype)

Dimension :  1
Size :  2
Shape :  (2,)
Data type :  <dtype: 'int32'>


# Modifying Variables

In [22]:
var=tf.Variable([5,4])
var.numpy()

array([5, 4])

### assign()

In [23]:
var[0].assign(7)
var.numpy()

array([7, 4])

### assign_add()

In [24]:
var.assign_add([9,0])
var.numpy()

array([16,  4])

### assign_sub()

In [25]:
var.assign_sub([9,1])
var.numpy()

array([7, 3])

# Reshaping and Changing Data Types of Variables

In [26]:
a=tf.Variable([1,2,3,4,5,6])
a.numpy()

array([1, 2, 3, 4, 5, 6])

### Reshaping

In [28]:
a_reshaped=tf.reshape(a,shape=(2,3))
a_reshaped.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

### DataType-Specifying the data type

In [29]:
a_float=tf.Variable([1,2,3,4],dtype=tf.float32)
a_float

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

# Arithmetic Operations

In [30]:
a=tf.Variable([9,2])
b=tf.Variable([1,2])
# Performing operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: tf.Tensor([10  4], shape=(2,), dtype=int32)
Subtraction: tf.Tensor([8 0], shape=(2,), dtype=int32)
Multiplication: tf.Tensor([9 4], shape=(2,), dtype=int32)
Division: tf.Tensor([9. 1.], shape=(2,), dtype=float64)


# Broadcasting

In [32]:
a=tf.Variable([9,2])
b=tf.Variable([2])
# Performing operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: tf.Tensor([11  4], shape=(2,), dtype=int32)
Subtraction: tf.Tensor([7 0], shape=(2,), dtype=int32)
Multiplication: tf.Tensor([18  4], shape=(2,), dtype=int32)
Division: tf.Tensor([4.5 1. ], shape=(2,), dtype=float64)
